import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../sanity'
import { Collection } from '../typings'
import { GetServerSideProps } from 'next'
import Link from 'next/link'
// import ollection from '../sanity'

interface Props {
  collections: Collection[]

}

const inter = Inter({ subsets: ['latin'] })

export default function Home({ collections }: Props) {

  return (
    <div className='max-w-7xl flex min-h-screen flex-col py-20 px-10 2xl:px-0 mx-auto'>
      <Head>
        <title>nft drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className='mb-10 text-3xl font-extralight'>
        the {''}
        <span className='font-extrabold underline decoration-pink-600/50'>papafam</span>{''}
        nft market place
      </h1>

      {/* <h6 className='text-100xl font-bold text-red-500 ' >helloo world</h6> */}
      <main className='bg-slate-100 p-10 shadow-2xl shadow-rose-400'>

        <div className='grid space-x-3 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4'>
          {collections && collections.map((collections) => (
             
             
            
          <div key ={collections._id} className='transition-all duration-200 hover:scale-105 flex flex-col items-center cursor-pointer'>
          
               <Link href={`/nft/${collections.slug.current}`}>
                <img className='h-30 w-40 rounded-2xl object-cover'  width={300} src={urlFor(collections.mainImage).url()} alt="" />
                </Link>
                <div className='p-5'>
                  <h2 className='text-3xl'>{collections.title}</h2>
                </div>
                
              </div>
             

          ))}
        </div>
      </main>
    </div>

  )
}

export const getServerSideProps: GetServerSideProps = async () => {

  const query = `*[_type == 'collection']
  {
    _id,
      title,
      address,
      nftCollectionName,
      mainImage{
      asset
      },
      previewImage{
      asset
      },
      slug{
      current
      },
      creator->{
        _id,
        name,
        address,
        slug
        {
          current
        }
      }
     
  }
  
  
  `

  const collections = await sanityClient.fetch(query)
  // console.log('this is collection name',collection.name)

  return {
    props: {
      collections
    }
  }
}
